# Generated by Django 3.0 on 2022-01-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('TXT', 'Textfile'), ('IMG', 'Imagefile')], default='TXT', max_length=255),
        ),
    ]
