# Generated by Django 4.0.3 on 2022-04-14 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_directory_parent_alter_file_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='height',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='file',
            name='width',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='directory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdirectories', to='website.directory'),
        ),
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='website.directory'),
        ),
    ]
